---
title: "Juvenile coral assemblage in Venezuela"
author: "LMM, ZM"
date: "August 19, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Packages

```{r}
library(tidyverse)
library(cowplot)
library(sjstats)
library(dplyr)
```

# 2. Data

```{r}
juve <- read_csv('data/reproduction.csv') %>% 
  rename(total_density = `Density (ind/m2)`)
```

# 3. Anova: Total density

```{r}
juve2 <- juve %>% 
  select(2, 6, 7, 8, 9) %>% 
  mutate(total_density = log(total_density+1))
```

```{r}
totald_anova <- anova(lm(total_density~Locality+
           Site%in%Locality+
           Transects%in%Locality%in%Site+
           Quadrats%in%Transects%in%Locality%in%Site, 
         data = juve2))
View(totald_anova)
```

```{r}
omega_sq(totald_anova, partial = FALSE, ci.lvl = NULL, n = 1000,
  method = c("dist", "quantile"))
```


# 4. Anova: Reproductive strategies

```{r}
strategies <- juve %>% 
  select(3, 4, 6, 7, 8, 9) %>% 
  gather(-c(Locality, Site, Transects, Quadrats), 
         value = density, key = strategy) %>% 
  mutate(density = log(density+1))
```

```{r}
strategy_anova <- anova(lm(density~strategy +
         strategy*Locality +
         strategy*Site%in%Locality+
         strategy*Transects%in%Site%in%Locality +
         strategy*Quadrats%in%Transects%in%Site%in%Locality,
         data = strategies))
View(strategy_anova)
```

```{r}
omega_sq(strategy_anova, partial = FALSE, ci.lvl = NULL, n = 1000,
  method = c("dist", "quantile"))
```
# 5. Plots

```{r}
if (!dir.exists('figures')){dir.create('figures')}
```

## 5.1 Total density

```{r}
total_a <- juve %>%
  ggplot(aes(x = Site, y = total_density, color = Locality)) +
  geom_jitter(size = 2.5, alpha = .5) +
  labs(y = expression(Density~(individuals/m^{2}))) +
  theme(legend.position = 'top')

total_b <- juve %>%
  group_by(Site, Locality) %>%
  summarise(avg=mean(total_density), std=sd(total_density)) %>% 
  ggplot(aes(x = Site, y = avg, fill = Locality)) +
  geom_col() +
  geom_errorbar(aes(ymin = avg, ymax = avg+std)) +
  labs(y = 'Mean density') +
  theme(legend.position = 'none')
  
plot_grid(total_a + theme(axis.title.x = element_blank(),
                          axis.text.x=element_blank()), 
          total_b + theme(axis.text.x = element_text(angle = 90)), 
          ncol = 1,
          labels = c('A', 'B'))

#ggsave('figures/fig01.svg')
```

## 5.2 Brooders vs spawners

```{r}
juve %>%
  filter(Brooders != 0 | Spawners != 0) %>% 
  ggplot(aes(x = Brooders, y = Spawners, color = Site)) +
  geom_jitter(size = 2.5, alpha = .6) +
  facet_grid(~Locality) +
  theme(legend.position = 'top')

#ggsave('figures/fig03_1.svg')
```

```{r}
juve %>%
  filter(Brooders != 0 | Spawners != 0) %>% 
  ggplot(aes(x = Spawners, y = Brooders, color = Site)) +
  geom_jitter(size = 2.5, alpha = .6) +
  facet_grid(~Locality) +
  theme(legend.position = 'top')

#ggsave('figures/fig03_2.svg')
```


